version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: contact-list-db
    environment:
      POSTGRES_DB: contactdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always
